### ISSUE TITLE
CGAL install issue

### ISSUE THREAD

**Issue by suptimq** [jkulhanek/tetra-nerf#10]
### issue
```bash
building wheels for collected packages: tetra-nerf
  Building wheel for tetra-nerf (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [124 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- The CXX compiler identification is GNU 9.4.0
      -- The CUDA compiler identification is NVIDIA 11.8.89
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Using torch libraries: /home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/lib
      -- Using torch includes: /home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include;/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/torch/csrc/api/include;/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/TH;/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/include/THC
      -- Using CUDA toolkit: /usr
      -- Using CUDA architectures: 86
      -- Using header-only CGAL
      -- Targetting Unix Makefiles
      -- Using /usr/bin/c++ compiler.
      -- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
      -- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.48")
      -- Boost include dirs: /usr/include
      -- Boost libraries:
      -- Using gcc version 4 or later. Adding -frounding-math
      -- pybind11 v2.9.2
      -- Found PythonInterp: /home/tian/anaconda3/envs/nerfstudio/bin/python (found version "3.8.16")
      -- Found PythonLibs: /home/tian/anaconda3/envs/nerfstudio/lib/libpython3.8.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE
      -- Found CUDA: /usr (found version "11.8")
      -- Configuring done (11.9s)
      -- Generating done (0.0s)
      CMake Warning:
        Manually-specified variables were not used by the project:
      
          EXAMPLE_VERSION_INFO
      
      
      -- Build files have been written to: /tmp/pip-req-build-zvbxs1_7
      [ 12%] Building NVCC ptx file build/traversal_generated_optix_traversal.cu.ptx
      [ 25%] compiling (and embedding ptx from)
      [ 37%] Building CUDA object CMakeFiles/tetranerf_cpp_extension.dir/src/tetrahedra_tracer.cu.o
      [ 50%] Building CXX object CMakeFiles/tetranerf_cpp_extension.dir/src/tetrahedra_tracer.cpp.o
      [ 62%] Building CXX object CMakeFiles/tetranerf_cpp_extension.dir/src/triangulation.cpp.o
      /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp:27:15: error: ‘Parallel_if_available_tag’ in namespace ‘CGAL’ does not name a type
         27 | typedef CGAL::Parallel_if_available_tag Concurrency_tag;
            |               ^~~~~~~~~~~~~~~~~~~~~~~~~
      /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp: In function ‘float find_average_spacing(size_t, float3*)’:
      /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp:75:56: error: ‘Concurrency_tag’ was not declared in this scope
         75 |     FT average_spacing = CGAL::compute_average_spacing<Concurrency_tag>(L, nb_neighbors);
            |                                                        ^~~~~~~~~~~~~~~
      /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp:75:88: error: no matching function for call to ‘compute_average_spacing<<expression error> >(std::vector<CGAL::Point_3<CGAL::Epick> >&, const unsigned int&)’
         75 |     FT average_spacing = CGAL::compute_average_spacing<Concurrency_tag>(L, nb_neighbors);
            |                                                                                        ^
      In file included from /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp:9:
      /usr/include/CGAL/compute_average_spacing.h:190:1: note: candidate: ‘template<class ConcurrencyTag, class PointRange, class T, class Tag, class Base> typename CGAL::Point_set_processing_3::GetK<PointRange, CGAL::Named_function_parameters<T, Tag, Base> >::Kernel::FT CGAL::compute_average_spacing(const PointRange&, unsigned int, const CGAL::Named_function_parameters<T, Tag, Base>&)’
        190 | compute_average_spacing(
            | ^~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/CGAL/compute_average_spacing.h:190:1: note:   template argument deduction/substitution failed:
      /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp:75:88: error: template argument 1 is invalid
         75 |     FT average_spacing = CGAL::compute_average_spacing<Concurrency_tag>(L, nb_neighbors);
            |                                                                                        ^
      In file included from /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp:9:
      /usr/include/CGAL/compute_average_spacing.h:284:1: note: candidate: ‘template<class ConcurrencyTag, class PointRange> typename CGAL::Point_set_processing_3::GetFT<PointRange>::type CGAL::compute_average_spacing(const PointRange&, unsigned int)’
        284 | compute_average_spacing(
            | ^~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/CGAL/compute_average_spacing.h:284:1: note:   template argument deduction/substitution failed:
      /tmp/pip-req-build-zvbxs1_7/src/triangulation.cpp:75:88: error: template argument 1 is invalid
         75 |     FT average_spacing = CGAL::compute_average_spacing<Concurrency_tag>(L, nb_neighbors);
            |                                                                                        ^
      make[2]: *** [CMakeFiles/tetranerf_cpp_extension.dir/build.make:116: CMakeFiles/tetranerf_cpp_extension.dir/src/triangulation.cpp.o] Error 1
      make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/tetranerf_cpp_extension.dir/all] Error 2
      make: *** [Makefile:91: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-zvbxs1_7/setup.py", line 122, in <module>
          setup(
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-zvbxs1_7/setup.py", line 63, in run
          self.build_extension(ext)
        File "/tmp/pip-req-build-zvbxs1_7/setup.py", line 108, in build_extension
          subprocess.run(["cmake", "--build", ".", *build_args], cwd=ext.sourcedir, check=True)
        File "/home/tian/anaconda3/envs/nerfstudio/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tetra-nerf
  Running setup.py clean for tetra-nerf
Failed to build tetra-nerf
ERROR: Could not build wheels for tetra-nerf, which is required to install pyproject.toml-based projects
```

### conda env
```bash
conda list
# packages in environment at /home/tian/anaconda3/envs/nerfstudio:
#
# Name                    Version                   Build  Channel
conda list
# packages in environment at /home/tian/anaconda3/envs/nerfstudio:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
asttokens                 2.2.1                    pypi_0    pypi
async-lru                 2.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
av                        10.0.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bidict                    0.22.1                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
blinker                   1.6.2                    pypi_0    pypi
ca-certificates           2023.01.10           h06a4308_0  
cachetools                5.3.0                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
cgal                      5.5.2.post202304111455          pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cmake                     3.26.3                   pypi_0    pypi
comm                      0.1.3                    pypi_0    pypi
configargparse            1.5.3                    pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cryptography              40.0.2                   pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dash                      2.9.3                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
debugpy                   1.6.7                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
descartes                 1.1.0                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docstring-parser          0.14.1                   pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.16.3                   pypi_0    pypi
filelock                  3.12.0                   pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
flask                     2.3.2                    pypi_0    pypi
fonttools                 4.39.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozendict                2.3.8                    pypi_0    pypi
gdown                     4.7.1                    pypi_0    pypi
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.31                   pypi_0    pypi
google-auth               2.18.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.28.1                   pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
ipykernel                 6.23.1                   pypi_0    pypi
ipython                   8.12.2                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.6                    pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jaxtyping                 0.2.19                   pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            8.2.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter-core              5.3.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-lsp               2.1.0                    pypi_0    pypi
jupyter-server            2.5.0                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.0.0                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.22.1                   pypi_0    pypi
jupyterlab-widgets        3.0.7                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lazy-loader               0.2                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lit                       16.0.5                   pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mediapy                   1.1.6                    pypi_0    pypi
mistune                   2.0.5                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.0.5                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
nbclassic                 1.0.0                    pypi_0    pypi
nbclient                  0.7.4                    pypi_0    pypi
nbconvert                 7.4.0                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nerfacc                   0.5.2                    pypi_0    pypi
nerfstudio                0.3.0                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
notebook                  6.5.4                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numpy                     1.24.3                   pypi_0    pypi
nuscenes-devkit           1.1.9                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
open3d                    0.17.0                   pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.1                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.1.2                   pypi_0    pypi
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.5.1                    pypi_0    pypi
plotly                    5.14.1                   pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
prompt-toolkit            3.0.38                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.5                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.6                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyequilib                 0.5.6                    pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyliblzfse                0.4.1                    pypi_0    pypi
pymeshlab                 2022.2.post4             pypi_0    pypi
pyngrok                   6.0.0                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.8.16               h7a1cb2a_3  
python-dateutil           2.8.2                    pypi_0    pypi
python-engineio           4.4.1                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
python-socketio           5.8.0                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.2                   pypi_0    pypi
qtconsole                 5.4.3                    pypi_0    pypi
qtpy                      2.3.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.30.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.3.5                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-image              0.20.0                   pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.9.1                    pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
sentry-sdk                1.23.1                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                66.0.0           py38h06a4308_0  
shapely                   2.0.1                    pypi_0    pypi
shtab                     1.6.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.4.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
stack-data                0.6.2                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2023.4.12                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tinycudann                1.7                      pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
torch                     2.0.1+cu118              pypi_0    pypi
torch-fidelity            0.3.0                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.15.2+cu118             pypi_0    pypi
tornado                   6.3.2                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
trimesh                   3.21.7                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typeguard                 4.0.0                    pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
tyro                      0.5.2                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
viser                     0.0.10                   pypi_0    pypi
wandb                     0.15.3                   pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
websockets                11.0.3                   pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0  
widgetsnbextension        4.0.7                    pypi_0    pypi
xatlas                    0.0.7                    pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
```

### cmake
```bash
cmake --version
cmake version 3.26.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by RubbishProgrammer** [comment]
I also have this problem. Have you solved it?

**Comment by jkulhanek** [comment]
I am sorry, I didn’t have time lately. I think the problem is with cgal version. I will check which version I am using. In the meantime can you please use the provided docker image?

**Comment by jkulhanek** [comment]
Ok, I'm using the same CGAL version 5.5.2

**Comment by jkulhanek** [comment]
Do you also have a CGAL library locally installed (outside the conda env)?

**Comment by suptimq** [comment]
No, I have only installed CGAL using conda

**Comment by RubbishProgrammer** [comment]
Thank you very much for your answer. I'll give it a try again.

**Comment by suptimq** [comment]
> 

If I remembered correctly, the error remained identical when I uninstall cgal using conda.

**Comment by jkulhanek** [comment]
If the error remained identical, it would mean that a different CGAL installation is picked up before the conda's one.

**Comment by Abc11c** [comment]
Hi,

I'm also facing the same issue, the docker installation seems to work but wanted to try out the biased sampler on a similar project, 

I found I have a CGAL local installation outside of cuda `ls  /usr/lib/x86_64-linux-gnu/cmake/CGAL` on installation of cgal=5.5.2 inside the conda env also doesn't solve the issue.

**Comment by kzwrime** [comment]
> Ok, I'm using the same CGAL version 5.5.2

I would like to request that you add the version requirements for CGAL to the README file https://github.com/jkulhanek/tetra-nerf#installation. This would be helpful for anyone to install your awesome project.
