### ISSUE TITLE
Error while running ns-train tetra-nerf - FileNotFoundError: [Errno 2] No such file or directory: 'data/train.npz'

### ISSUE THREAD

**Issue by pradeepuNIT** [jkulhanek/tetra-nerf#23]
[09:56:57] Saving config to: outputs/unnamed/tetra-nerf/2023-10-10_095657/config.yml            experiment_config.py:129
[09:56:57] Saving checkpoints to: outputs/unnamed/tetra-nerf/2023-10-10_095657/nerfstudio_models          trainer.py:139
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/nerfstudio/scripts/train.py", line 247, in entrypoint
    main(
  File "/home/user/nerfstudio/scripts/train.py", line 233, in main
    launch(
  File "/home/user/nerfstudio/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/nerfstudio/scripts/train.py", line 86, in train_loop
    trainer.setup()
  File "/home/user/nerfstudio/nerfstudio/engine/trainer.py", line 152, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/user/nerfstudio/nerfstudio/configs/base_config.py", line 60, in setup
    return self._target(self, **kwargs)
  File "/home/user/tetra-nerf/tetranerf/nerfstudio/pipeline.py", line 29, in __init__
    self.datamanager: VanillaDataManager = config.datamanager.setup(
  File "/home/user/nerfstudio/nerfstudio/configs/base_config.py", line 60, in setup
    return self._target(self, **kwargs)
  File "/home/user/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 413, in __init__
    self.train_dataparser_outputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/home/user/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 163, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split)
  File "/home/user/nerfstudio/nerfstudio/data/dataparsers/minimal_dataparser.py", line 53, in _generate_dataparser_outputs
    data = np.load(filepath, allow_pickle=True)
  File "/home/user/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/train.npz'

Getting above filenotfound error while running "ns-train tetra-nerf --pipeline.model.tetrahedra-path <data folder>/sparse.th minimal-parser --data <data folder>"

Can someone help?

**Comment by jkulhanek** [comment]
Hi, sorry for the late response. You have to point —data to an existing dataset root. Where do you store the dataset? Did you follow README on how to prepare the data?
