### ISSUE TITLE
RuntimeError: OPTIX_ERROR_ENTRY_SYMBOL_NOT_FOUND: Optix call 'optixInit()' failed

### ISSUE THREAD

**Issue by Evergreen0929** [jkulhanek/tetra-nerf#27]
Everything is going well until I meet this issue:

`Tetrahedra initialized from file data/blender/chair/pointnerf-0.5.th:
    Num points: 174525
    Num tetrahedra: 1087454
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.1440
VanillaPipeline.get_train_loss_dict: 0.1436
Traceback (most recent call last):
  File "/root/anaconda3/envs/tetra/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 259, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 479, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/pipelines/base_pipeline.py", line 299, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/mnt/c/Users/IVC-LAB-7/study/research/Computer_Graphics/tetra-nerf/tetranerf/nerfstudio/model.py", line 525, in get_outputs
    tracer = self.get_tetrahedra_tracer()
  File "/mnt/c/Users/IVC-LAB-7/study/research/Computer_Graphics/tetra-nerf/tetranerf/nerfstudio/model.py", line 405, in get_tetrahedra_tracer
    self._tetrahedra_tracer = TetrahedraTracer(device)
RuntimeError: OPTIX_ERROR_ENTRY_SYMBOL_NOT_FOUND: Optix call 'optixInit()' failed: /mnt/c/Users/IVC-LAB-7/study/research/Computer_Graphics/tetra-nerf/src/tetrahedra_tracer.cpp:110)

Traceback (most recent call last):
  File "/root/anaconda3/envs/tetra/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 259, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/engine/trainer.py", line 479, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/pipelines/base_pipeline.py", line 299, in get_train_loss_dict
    model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/tetra/lib/python3.9/site-packages/nerfstudio/models/base_model.py", line 142, in forward
    return self.get_outputs(ray_bundle)
  File "/mnt/c/Users/IVC-LAB-7/study/research/Computer_Graphics/tetra-nerf/tetranerf/nerfstudio/model.py", line 525, in get_outputs
    tracer = self.get_tetrahedra_tracer()
  File "/mnt/c/Users/IVC-LAB-7/study/research/Computer_Graphics/tetra-nerf/tetranerf/nerfstudio/model.py", line 405, in get_tetrahedra_tracer
    self._tetrahedra_tracer = TetrahedraTracer(device)
RuntimeError: OPTIX_ERROR_ENTRY_SYMBOL_NOT_FOUND: Optix call 'optixInit()' failed: /mnt/c/Users/IVC-LAB-7/study/research/Computer_Graphics/tetra-nerf/src/tetrahedra_tracer.cpp:110)`

**Comment by Evergreen0929** [comment]
I have tried re-install GPU driver, and re-install Optix 7.6 / 7.5. Not working. Could you please help me figure out this issue? My GPU is 4090 with Driver Version: 546.65 and CUDA Version: 12.3 (the latest).

**Comment by Evergreen0929** [comment]
Additionally, I am using windows wsl. Hope this will not cause unexcepted conflicts.

**Comment by jkulhanek** [comment]
Sorry for the late reply. Are you still having issues? I think the error is caused by incompatibility between OptiX, driver, and CUDA. In my case, I always used CUDA<12. If you use CUDA 12.3, are you sure the actual library to which you are linking matches it? Because tetranerf will link to libtorch (pytorch) which bundles its own CUDA and the torch's cuda version must match the CUDA version you've installed.
